### ISSUE TITLE
Use vararg keyword arguments for connect() convenience function

### ISSUE THREAD

**Issue by nalimilan** [NCarson/Postgres#1]
I was just giving a look at the API, and I noticed a small improvement you could make to `connect`. Instead of:

``` julia
function Base.connect(::Type{PostgresServer}, d::Dict)
```

you could do:

``` julia
function Base.connect(::Type{PostgresServer}; args...)
```

This would allow users to write `connect(PostgresServer, db="julia_test", host="localhost")` instead of `connect(PostgresServer, Dict(:db=>"julia_test", :host=>"localhost"))`.

For more details, see http://docs.julialang.org/en/latest/manual/functions/#keyword-arguments

My two cents...

**Comment by NCarson** [comment]
That is a lot better.  I did not realize that kwargs were supported.  The dict idea was basically a workaround for positional defaults. Still new to Julia.

**Comment by NCarson** [comment]
Changed on head.

**Comment by nalimilan** [comment]
Cool.
